#넘파이의 사용

1. 데이터 분석 프로젝트: 수치형 데이터의 요약, 통계, 시각화
2. 이미지 처리 프로젝트: 이미지 분석
3. 게임, 시뮬레이션 프로그램: 수치 시뮬레이션 들을 구현
3. 머신러닝/딥러닝 모델 프로젝트: 금융, 의료, 실험, 센서 데이터 

In [5]:
import numpy as np

In [6]:
data = [
    [120, 135, 150, 145],  # 제품A
    [100, 110, 140, 130],  # 제품B
    [90, 100, 95, 105] ]

data

[[120, 135, 150, 145], [100, 110, 140, 130], [90, 100, 95, 105]]

In [7]:
np.array(data)

array([[120, 135, 150, 145],
       [100, 110, 140, 130],
       [ 90, 100,  95, 105]])

In [8]:
sales_data = np.array(data)
np.sum(sales_data, axis=1) # 총 판매량 

array([550, 480, 390])

In [9]:
#총 이익
profit_per_unit = np.array([20,30,25])
total_sales = np.dot(profit_per_unit, sales_data) #총 판매 금액 

# 이미지처리

In [10]:
from PIL import Image
img = Image.open('image-26.jpg').convert('L')
img_ary = np.array(img)
new_img = np.clip(img_ary+10,100,255).astype(np.uint8)
Image.fromarray(new_img).save('new_sample.jpg')

FileNotFoundError: [Errno 2] No such file or directory: 'image-26.jpg'

In [ ]:
inverted = 255-img_ary
Image.fromarray(inverted).save('new_sample2.jpg')

# 데이터 시뮬레이션


In [ ]:
import matplotlib.pyplot as plt

n_step = 1000
step = np.random.choice([-1,1], size=n_step)
walk = np.cumsum(step)

plt.plot(walk)

In [ ]:
#배열의 속성
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

#배열의 속성 확인
print('배열의 차원: ', arr.ndim)
print('배열의 형태: ', arr.shape)
print('배열의 크기: ', arr.size)
print('배열의 데이터 타입: ',arr.dtype)
print('배열 요소의 크기: ', arr.itemsize)
print('배열의 strides: ', arr.strides)


In [ ]:
# 3차원: 텐서를 위한 리스트 생성 
tensor_list =[[[1,2,3,4],[1,2,3,4],[1,2,3,4]], #4,3,4
#              [[1,2,3,4],[1,2,3,4],[1,2,3,4]], #2,3,4
#              [[1,2,3,4],[1,2,3,4],[1,2,3,4]],
              [[1,2,3,4],[1,2,3,4],[1,2,3,4]]]

tensor_list

In [ ]:
# 텐서 
arr1 = np.array(tensor_list)
type(arr1)

In [ ]:
arr1.shape #x,y,z > 면행열

In [ ]:
arr3 = np.array([1,2,3]) #1차원
type(arr3)

In [ ]:
arr.dtype, arr3.dtype

In [ ]:
arr4 = np.array([1,2,3,]) #1차원, array를 생성하는 함수이다 
id(arr3), id(arr4)

In [ ]:
# type 변환 
list2 = [1,2,4,'5',10]
arr5 = np.array(list2)
arr5
type(list2), arr5.dtype

In [ ]:
np.array(list2, int)

# shape 속성


In [11]:
list2 = [1,2,3,4,5,6,7,8]
t_2 = np.array(list2)
t_2.shape, t_2.ndim

((8,), 1)

In [12]:
#4,3
list3 = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
t_3 = np.array(list3)
t_3.shape, t_3.shape

((4, 3), (4, 3))

In [13]:
list4 = range(1,13)
#reshape((row,column))
np.array(list4).reshape((3,4)), np.array(list4).reshape((4,3))

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]))

In [14]:
list4 = np.array([1,2,3])
list4.reshape((3,1))

array([[1],
       [2],
       [3]])

In [15]:
#newaxis 키워드 !!
#list4.reshape((1,3))
list4[np.newaxis, :]

array([[1, 2, 3]])

In [ ]:
# arange()
# range(시작, 끝, 스탭)


In [ ]:
np.arange(10)

In [ ]:
np.arange(-5,5)

# method chaining

In [ ]:
#2,3 > 2행 3열 
np.arange(1,7).reshape((2,3))

In [ ]:
np.arange(1,25).reshape((2,3,4))

In [ ]:

#2,3,4 >3*4*2
#24,1 -> [],[],[],[], ... 이렇게 된다
np.arange(1,25).reshape((2,3,4)).reshape((24))



In [ ]:
# 기본차원으로 바꿔!!!
np.arange(1,25).reshape((2,3,4)).reshape(-1)

In [ ]:
#리스트로부터 배열 생성 
arr1 = np.array([1,2,3,4,5])
print('1.',arr1)
# 0으로 채워진 배열 생성 
arr2 = np.zeros(5)
print('2.',arr2)
#1로 채워진 배열 생성 
arr3 = np.ones((3,3))
print('3.',arr3)
#1-10까지 2씩 증가하는 배열
range_arr = np.arange(1,10,2)
print('4.',range_arr)
# 0부터 100까지 5개의 숫자를 균들 간격으로 생성
linspace_arr = np.linspace(0,100,5)
print(linspace_arr)
# 2행 3열의 랜덤 값 배열 (0-1 사이)
random_arr = np.random.rand(2,3)
print(random_arr)


1. [1 2 3 4 5]
2. [0. 0. 0. 0. 0.]
3. [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
4. [1 3 5 7 9]
[  0.  25.  50.  75. 100.]
[[0.08057193 0.44585412 0.05788972]
 [0.88306482 0.72858121 0.48140913]]


In [ ]:
#2dim array create
#앞에부터 붙어 있는 괄호들의 개수를 보면 dim 알 수 있음 
arr = np.array([[1,2],[3,4]])
print(arr)

## 단위행렬과 대각행렬의 생성 

In [ ]:
# 3x3 단위행렬 생성
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#대각원소가 [1,2,3]인 대각행렬 생성
diagonal_matrix = np.diag([1, 2, 3])
print(diagonal_matrix)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
a = np.arange(9).reshape(3,3)
diagonal_matrix_value = np.diag(a)
print(diagonal_matrix_value )

[0 4 8]


In [ ]:
# 3x3 단위행렬 생성 (N=3)
eye_matrix = np.eye(3)
print(eye_matrix)

# 4x3 직사각형 행렬 생성 (N=4, M=3)
rect_eye = np.eye(4, 3)
print(rect_eye)


# k 매개변수로 대각선 위치 조정 (k=1은 주대각선 위로 한 칸)
shifted_eye = np.eye(3, k=1)
print(shifted_eye)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [ ]:
# 기존 배열
arr = np.array([[1, 2, 3], [4, 5, 6]])

# empty_like(): 초기화되지 않은 배열 생성
# 틀을 빠르게 찍어냄? 이상한 수가 나올 수 있음 
#기존 배열을 참고해서 똑같은 틀을 복제??? 아마도 
empty_arr = np.empty_like(arr)

# zeros_like(): 0으로 채워진 배열 생성
zeros_arr = np.zeros_like(arr)

# ones_like(): 1로 채워진 배열 생성
ones_arr = np.ones_like(arr)

# full_like(): 지정된 값으로 채워진 배열 생성
full_arr = np.full_like(arr, 7)  # 7로 채워진 배열

print("원본 배열의 shape:", arr.shape)
print("zeros_like 결과:\n", zeros_arr)
print("ones_like 결과:\n", ones_arr)
print("full_like 결과:\n", full_arr)


원본 배열의 shape: (2, 3)
zeros_like 결과:
 [[0 0 0]
 [0 0 0]]
ones_like 결과:
 [[1 1 1]
 [1 1 1]]
full_like 결과:
 [[7 7 7]
 [7 7 7]]


In [ ]:
#numpy의 난수 생성 함수 
# 난수 =  random_number 
# 0과 1 사이의 균일 분포 난수
random_uniform = np.random.rand(2, 3)  # 2x3 행렬
print(random_uniform)

# 표준 정규 분포 난수
random_normal = np.random.randn(2, 3)  # 2x3 행렬
print(random_normal)

# 정수 난수 (최소값, 최대값-1, 크기)
random_int = np.random.randint(0, 10, (2, 3))  # 0~9 사이의 정수로 된 2x3 행렬
print(random_int)

# 시드 설정 - 재현 가능한 난수 생성
np.random.seed(42)
random_seeded = np.random.rand(3)
print(random_seeded)

[[0.97558921 0.97341813 0.77836514]
 [0.52360898 0.15120858 0.1465711 ]]
[[-0.01048166 -0.83681121  0.59148048]
 [ 2.10569884  1.21053463 -0.27126607]]
[[3 3 6]
 [4 9 1]]
[0.37454012 0.95071431 0.73199394]


# numpy -> 숫자와 관련 된 함수들!

In [ ]:
lst_data = [1,2,3]+[4,5,6] #__add__() append() extend()
lst_data


[1, 2, 3, 4, 5, 6]

In [ ]:
a1  = np.array(lst_data)
print(a1+2)

[3 4 5 6 7 8]


In [ ]:
a2 = np.array([2,3,4,5,6,3]) #array의 행렬이 같아야 요소별 연산을 한다 
print(a1+a2)

[ 3  5  7  9 11  9]


##브로드캐스팅

크기가 다른 배열에서 작은쪽이 큰쪽에 맞춰 크기를 확장하는 기능 

In [ ]:
a_array = np.arange(3)
b_array = np.arange(3)[:, np.newaxis]
print(b_array, a_array)
print(b_array+a_array)

# 0 0 0    0 1 2        0 1 2
# 1 1 1    0 1 2        1 2 3
# 2 2 2    0 1 2        2 3 4 

[[0]
 [1]
 [2]] [0 1 2]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
# shape이 같은 배열 간의 연산
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("덧셈:\n", a + b)
print("뺄셈:\n", a - b)
print("곱셈:\n", a * b)
print("나눗셈:\n", a / b)

# shape이 다른 경우 오류 발생
c = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
d = np.array([[1, 2], [3, 4]])        # shape: (2, 2)

# shape이 맞지 않는 배열 간의 연산을 수행하려면 > reshape() 사용 > shape 먼저 맞추거나 브로드캐스팅 규칙에 부합하도록 배열 수정 

덧셈:
 [[ 6  8]
 [10 12]]
뺄셈:
 [[-4 -4]
 [-4 -4]]
곱셈:
 [[ 5 12]
 [21 32]]
나눗셈:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# 배열의 각 요소에 대해 개별적인 비교, 배열의 모든 요소에 대해 동시 적용
#비교 연산 
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,3,3,0,5])

#각각의 요소 같음 비교
print("같음: ", arr1 == arr2)

#크기 비교
print("더 큼:", arr1 > arr2) 
print("더 작음:", arr1 < arr2)  

# 논리 연산 결합
mask = (arr1 >= 3) & (arr2 <= 4)
print("복합 조건:", mask)  

# 비교 결과를 이용한 필터링
filtered = arr1[arr1 > 3]
print("3보다 큰 값:", filtered)  

같음:  [ True False  True False  True]
더 큼: [False False False  True False]
더 작음: [False  True False False False]
복합 조건: [False False  True  True False]
3보다 큰 값: [4 5]


In [ ]:
# 요소별 연산돠 벡터화 연산 
a = np.array([1,2,3])
b = np.array([4,5,6])

print('add: ', a+b)
print('multipy: ', a*b)
print('square: ', np.square(a))
print('square root: ', np.sqrt(a))

add:  [5 7 9]
multipy:  [ 4 10 18]
square:  [1 4 9]
square root:  [1.         1.41421356 1.73205081]


In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6,7])
np.concatenate([v1,v2], axis=0)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
grid = np.array([[1,2,3],[1,2,3]])
np.concatenate([grid,grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [ ]:
grid = np.array([[1,2,3],[1,2,3]])
np.concatenate([grid,grid], axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.vstack([v1,v1]) #vertical

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
np.hstack([v1,v2]) #horizontal

array([1, 2, 3, 4, 5, 6, 7])

# 축 인덱싱 

axis = 0
axis = 1
axis = 2

In [ ]:
# 축인덱싱 

#2차원 배열 예제
arr_2d = np.array([[1,2,3],
                   [4,5,6]])
np.sum(arr_2d,)

np.int64(21)

## 배열의 인덱싱

배열[행인덱스, 열인덱스]

In [ ]:
arr = np.array([1,2,3,4,5])
arr[0], arr[-1], 
arr_2d[1,1]=10

In [ ]:
arr_2d

array([[ 1,  2,  3],
       [ 4, 10,  6]])

In [ ]:
arr = np.array([0, 1, 2, 3, 4, 5])
arr[2:]

array([2, 3, 4, 5])

## 슬라이싱

[:] 전체
[0:n] 0~n-1 까지
[:5] 0~4까지

리스트와 차이점
- 리스트 :  복사본 리턴
- 배열 : 원본 배열의 뷰 -> 복사 x 원본에도 영향을 미친다
- 슬라이싱.copy()

In [ ]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

In [ ]:
x[4:7]

array([4, 5, 6])

In [ ]:
new_x = x[4:7]


In [ ]:
new_x[0] = 100
new_x,x #view 뷔의 값을 변경하면 원본의 값도 바뀐다

(array([100,   5,   6]),
 array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9]))

In [ ]:
new_x1 = x[4:7].copy()
new_x1[0] = 200

new_x,x,new_x1

(array([100,   5,   6]),
 array([  0,   1,   2,   3, 100,   5,   6,   7,   8,   9]),
 array([200,   5,   6]))

2차원: 배열명[열, 행]
3차원: 배열명[시작 면 번호:종료 면 번호1:간격,시작 행 번호:종료 행 번호1:간격, 시작 열 번호:종료 열 번호1,간격]

In [ ]:
import numpy as np

# 기준이 될 4x4 배열 생성 (이미지와 동일하게 0부터 15까지의 숫자로 채움)
arr_2d = np.arange(16).reshape((4, 4))

print("원본 4x4 배열:")
print(arr_2d)
print("-" * 30)

원본 4x4 배열:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------------------------


In [ ]:
# 첫 번째 행 전체
arr_2d[0,:]

array([0, 1, 2, 3])

In [ ]:
#마지막 열 전체
arr_2d[:,-1]

array([ 3,  7, 11, 15])

In [ ]:
#첫 번째 행과 마지막 행만 선택, 각 행의 첫번째, 마지막 열 선택
arr_2d[[0, -1], :][:, [0, -1]]

array([[ 0,  3],
       [12, 15]])

In [ ]:
# 짝수 인덱스 행(0번째, 2번째 행), 홀수 인덱스 열 선택
arr_2d[0:3:2, :][:, 1:4:2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
#세번째 층, 두번째 행에서 네번째 행, 홀수 인덱스 열
arr_3_1 = np.arange(36).reshape(6,6)
arr_3_2 = np.arange(36).reshape(6,6)
arr_3_3 = np.arange(36).reshape(6,6)
arr_3_4 = np.arange(36).reshape(6,6)

arr_3d = np.stack([arr_3_1, arr_3_2, arr_3_3, arr_3_4])

arr_3d


array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [ ]:
# 원본 2차원 배열
base = np.arange(36).reshape(6, 6)

# np.tile을 사용해서 3차원 배열 만들기
# 먼저 (1,6,6)로 차원을 맞춘 다음, tile로 (4,6,6) 복제
arr_3d_2 = np.tile(base[np.newaxis, :, :], (4, 1, 1))

arr_3d_2

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [ ]:
arr_3d_3 = np.array([np.arange(36).reshape(6, 6) for _ in range(4)])
arr_3d_3
# 느리니 추천하지 않음 

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]],

       [[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [ ]:

# 2번째 층 선택
arr_3d[1]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [ ]:
#네번째행, 두번째 열 원소 선택, 1차원 배열로 작성

arr_3d[:,3,1]

array([19, 19, 19, 19])

In [ ]:
#배열의 첫 두 층, 마지막 두 행, 마지막 두 열 선택
arr_3d[:2,-2:,-2:]

array([[[28, 29],
        [34, 35]],

       [[28, 29],
        [34, 35]]])

In [ ]:
#짝수 인덱스층, 모든행의 세번째열 선택
arr_3d[::2,:,4]

array([[ 4, 10, 16, 22, 28, 34],
       [ 4, 10, 16, 22, 28, 34]])

In [ ]:
#세번째 층, 두번째 행에서 네번째 행, 홀수 인덱스 열
arr_3d[-2,1:4,1::2]

array([[ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23]])